on:
  push:
    tags:
      - 'v[0-9][0-9][0-9][0-9][01][0-9][0-3][0-9][0-2][0-9][0-5][0-9][0-5][0-9]'
jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets:
      pypi_password: ${{ secrets.pypi_password }}